// Hiragana characters
export const hiragana = [
  { japanese: 'あ', romaji: 'a', english: 'a', type: 'hiragana' },
  { japanese: 'い', romaji: 'i', english: 'i', type: 'hiragana' },
  { japanese: 'う', romaji: 'u', english: 'u', type: 'hiragana' },
  { japanese: 'え', romaji: 'e', english: 'e', type: 'hiragana' },
  { japanese: 'お', romaji: 'o', english: 'o', type: 'hiragana' },
  { japanese: 'か', romaji: 'ka', english: 'ka', type: 'hiragana' },
  { japanese: 'き', romaji: 'ki', english: 'ki', type: 'hiragana' },
  { japanese: 'く', romaji: 'ku', english: 'ku', type: 'hiragana' },
  { japanese: 'け', romaji: 'ke', english: 'ke', type: 'hiragana' },
  { japanese: 'こ', romaji: 'ko', english: 'ko', type: 'hiragana' },
  { japanese: 'さ', romaji: 'sa', english: 'sa', type: 'hiragana' },
  { japanese: 'し', romaji: 'shi', english: 'shi', type: 'hiragana' },
  { japanese: 'す', romaji: 'su', english: 'su', type: 'hiragana' },
  { japanese: 'せ', romaji: 'se', english: 'se', type: 'hiragana' },
  { japanese: 'そ', romaji: 'so', english: 'so', type: 'hiragana' },
  { japanese: 'た', romaji: 'ta', english: 'ta', type: 'hiragana' },
  { japanese: 'ち', romaji: 'chi', english: 'chi', type: 'hiragana' },
  { japanese: 'つ', romaji: 'tsu', english: 'tsu', type: 'hiragana' },
  { japanese: 'て', romaji: 'te', english: 'te', type: 'hiragana' },
  { japanese: 'と', romaji: 'to', english: 'to', type: 'hiragana' },
  { japanese: 'な', romaji: 'na', english: 'na', type: 'hiragana' },
  { japanese: 'に', romaji: 'ni', english: 'ni', type: 'hiragana' },
  { japanese: 'ぬ', romaji: 'nu', english: 'nu', type: 'hiragana' },
  { japanese: 'ね', romaji: 'ne', english: 'ne', type: 'hiragana' },
  { japanese: 'の', romaji: 'no', english: 'no', type: 'hiragana' },
  { japanese: 'は', romaji: 'ha', english: 'ha', type: 'hiragana' },
  { japanese: 'ひ', romaji: 'hi', english: 'hi', type: 'hiragana' },
  { japanese: 'ふ', romaji: 'fu', english: 'fu', type: 'hiragana' },
  { japanese: 'へ', romaji: 'he', english: 'he', type: 'hiragana' },
  { japanese: 'ほ', romaji: 'ho', english: 'ho', type: 'hiragana' },
  { japanese: 'ま', romaji: 'ma', english: 'ma', type: 'hiragana' },
  { japanese: 'み', romaji: 'mi', english: 'mi', type: 'hiragana' },
  { japanese: 'む', romaji: 'mu', english: 'mu', type: 'hiragana' },
  { japanese: 'め', romaji: 'me', english: 'me', type: 'hiragana' },
  { japanese: 'も', romaji: 'mo', english: 'mo', type: 'hiragana' },
  { japanese: 'や', romaji: 'ya', english: 'ya', type: 'hiragana' },
  { japanese: 'ゆ', romaji: 'yu', english: 'yu', type: 'hiragana' },
  { japanese: 'よ', romaji: 'yo', english: 'yo', type: 'hiragana' },
  { japanese: 'ら', romaji: 'ra', english: 'ra', type: 'hiragana' },
  { japanese: 'り', romaji: 'ri', english: 'ri', type: 'hiragana' },
  { japanese: 'る', romaji: 'ru', english: 'ru', type: 'hiragana' },
  { japanese: 'れ', romaji: 're', english: 're', type: 'hiragana' },
  { japanese: 'ろ', romaji: 'ro', english: 'ro', type: 'hiragana' },
  { japanese: 'わ', romaji: 'wa', english: 'wa', type: 'hiragana' },
  { japanese: 'を', romaji: 'wo', english: 'wo', type: 'hiragana' },
  { japanese: 'ん', romaji: 'n', english: 'n', type: 'hiragana' }
];

// Katakana characters
export const katakana = [
  { japanese: 'ア', romaji: 'a', english: 'a', type: 'katakana' },
  { japanese: 'イ', romaji: 'i', english: 'i', type: 'katakana' },
  { japanese: 'ウ', romaji: 'u', english: 'u', type: 'katakana' },
  { japanese: 'エ', romaji: 'e', english: 'e', type: 'katakana' },
  { japanese: 'オ', romaji: 'o', english: 'o', type: 'katakana' },
  { japanese: 'カ', romaji: 'ka', english: 'ka', type: 'katakana' },
  { japanese: 'キ', romaji: 'ki', english: 'ki', type: 'katakana' },
  { japanese: 'ク', romaji: 'ku', english: 'ku', type: 'katakana' },
  { japanese: 'ケ', romaji: 'ke', english: 'ke', type: 'katakana' },
  { japanese: 'コ', romaji: 'ko', english: 'ko', type: 'katakana' },
  { japanese: 'サ', romaji: 'sa', english: 'sa', type: 'katakana' },
  { japanese: 'シ', romaji: 'shi', english: 'shi', type: 'katakana' },
  { japanese: 'ス', romaji: 'su', english: 'su', type: 'katakana' },
  { japanese: 'セ', romaji: 'se', english: 'se', type: 'katakana' },
  { japanese: 'ソ', romaji: 'so', english: 'so', type: 'katakana' },
  { japanese: 'タ', romaji: 'ta', english: 'ta', type: 'katakana' },
  { japanese: 'チ', romaji: 'chi', english: 'chi', type: 'katakana' },
  { japanese: 'ツ', romaji: 'tsu', english: 'tsu', type: 'katakana' },
  { japanese: 'テ', romaji: 'te', english: 'te', type: 'katakana' },
  { japanese: 'ト', romaji: 'to', english: 'to', type: 'katakana' },
  { japanese: 'ナ', romaji: 'na', english: 'na', type: 'katakana' },
  { japanese: 'ニ', romaji: 'ni', english: 'ni', type: 'katakana' },
  { japanese: 'ヌ', romaji: 'nu', english: 'nu', type: 'katakana' },
  { japanese: 'ネ', romaji: 'ne', english: 'ne', type: 'katakana' },
  { japanese: 'ノ', romaji: 'no', english: 'no', type: 'katakana' },
  { japanese: 'ハ', romaji: 'ha', english: 'ha', type: 'katakana' },
  { japanese: 'ヒ', romaji: 'hi', english: 'hi', type: 'katakana' },
  { japanese: 'フ', romaji: 'fu', english: 'fu', type: 'katakana' },
  { japanese: 'ヘ', romaji: 'he', english: 'he', type: 'katakana' },
  { japanese: 'ホ', romaji: 'ho', english: 'ho', type: 'katakana' },
  { japanese: 'マ', romaji: 'ma', english: 'ma', type: 'katakana' },
  { japanese: 'ミ', romaji: 'mi', english: 'mi', type: 'katakana' },
  { japanese: 'ム', romaji: 'mu', english: 'mu', type: 'katakana' },
  { japanese: 'メ', romaji: 'me', english: 'me', type: 'katakana' },
  { japanese: 'モ', romaji: 'mo', english: 'mo', type: 'katakana' },
  { japanese: 'ヤ', romaji: 'ya', english: 'ya', type: 'katakana' },
  { japanese: 'ユ', romaji: 'yu', english: 'yu', type: 'katakana' },
  { japanese: 'ヨ', romaji: 'yo', english: 'yo', type: 'katakana' },
  { japanese: 'ラ', romaji: 'ra', english: 'ra', type: 'katakana' },
  { japanese: 'リ', romaji: 'ri', english: 'ri', type: 'katakana' },
  { japanese: 'ル', romaji: 'ru', english: 'ru', type: 'katakana' },
  { japanese: 'レ', romaji: 're', english: 're', type: 'katakana' },
  { japanese: 'ロ', romaji: 'ro', english: 'ro', type: 'katakana' },
  { japanese: 'ワ', romaji: 'wa', english: 'wa', type: 'katakana' },
  { japanese: 'ヲ', romaji: 'wo', english: 'wo', type: 'katakana' },
  { japanese: 'ン', romaji: 'n', english: 'n', type: 'katakana' }
];

// Common Japanese travel phrases
export const phrases = [
  // Basic Greetings & Courtesy
  { japanese: 'おはよう', romaji: 'ohayou', english: 'Good morning (casual)', type: 'phrase' },
  { japanese: 'おはようございます', romaji: 'ohayou gozaimasu', english: 'Good morning (polite)', type: 'phrase' },
  { japanese: 'こんにちは', romaji: 'konnichiwa', english: 'Hello / Good afternoon', type: 'phrase' },
  { japanese: 'こんばんは', romaji: 'konbanwa', english: 'Good evening', type: 'phrase' },
  { japanese: 'ありがとう', romaji: 'arigatou', english: 'Thank you (casual)', type: 'phrase' },
  { japanese: 'ありがとうございます', romaji: 'arigatou gozaimasu', english: 'Thank you (polite)', type: 'phrase' },
  { japanese: 'どうもありがとうございます', romaji: 'doumo arigatou gozaimasu', english: 'Thank you very much', type: 'phrase' },
  { japanese: 'すみません', romaji: 'sumimasen', english: 'Excuse me / Sorry', type: 'phrase' },
  { japanese: 'ごめんなさい', romaji: 'gomen nasai', english: 'I\'m sorry', type: 'phrase' },
  { japanese: 'さようなら', romaji: 'sayounara', english: 'Goodbye', type: 'phrase' },
  { japanese: 'じゃあね', romaji: 'jaa ne', english: 'See you (casual)', type: 'phrase' },
  { japanese: 'また会いましょう', romaji: 'mata aimashou', english: 'See you again', type: 'phrase' },
  { japanese: 'はい', romaji: 'hai', english: 'Yes', type: 'phrase' },
  { japanese: 'いいえ', romaji: 'iie', english: 'No', type: 'phrase' },
  { japanese: 'お願いします', romaji: 'onegaishimasu', english: 'Please', type: 'phrase' },
  { japanese: 'どういたしまして', romaji: 'douitashimashite', english: 'You\'re welcome', type: 'phrase' },
  { japanese: 'おやすみなさい', romaji: 'oyasuminasai', english: 'Good night', type: 'phrase' },
  { japanese: 'はじめまして', romaji: 'hajimemashite', english: 'Nice to meet you', type: 'phrase' },
  { japanese: 'よろしくお願いします', romaji: 'yoroshiku onegaishimasu', english: 'Please treat me well', type: 'phrase' },
  { japanese: 'お元気ですか', romaji: 'ogenki desu ka', english: 'How are you?', type: 'phrase' },

  // Communication
  { japanese: '英語を話せますか', romaji: 'eigo wo hanasemasu ka', english: 'Do you speak English?', type: 'phrase' },
  { japanese: '日本語がわかりません', romaji: 'nihongo ga wakarimasen', english: 'I don\'t understand Japanese', type: 'phrase' },
  { japanese: 'わかりました', romaji: 'wakarimashita', english: 'I understand', type: 'phrase' },
  { japanese: 'わかりません', romaji: 'wakarimasen', english: 'I don\'t understand', type: 'phrase' },
  { japanese: 'もう一度お願いします', romaji: 'mou ichido onegaishimasu', english: 'One more time please', type: 'phrase' },
  { japanese: 'ゆっくり話してください', romaji: 'yukkuri hanashite kudasai', english: 'Please speak slowly', type: 'phrase' },
  { japanese: '書いてください', romaji: 'kaite kudasai', english: 'Please write it down', type: 'phrase' },
  { japanese: 'これは何ですか', romaji: 'kore wa nan desu ka', english: 'What is this?', type: 'phrase' },
  { japanese: 'どういう意味ですか', romaji: 'dou iu imi desu ka', english: 'What does it mean?', type: 'phrase' },

  // Transportation - Train/Subway
  { japanese: '駅はどこですか', romaji: 'eki wa doko desu ka', english: 'Where is the station?', type: 'phrase' },
  { japanese: '切符売り場はどこですか', romaji: 'kippu uriba wa doko desu ka', english: 'Where is the ticket counter?', type: 'phrase' },
  { japanese: '何番線ですか', romaji: 'nanban sen desu ka', english: 'Which platform?', type: 'phrase' },
  { japanese: '新宿まで一枚ください', romaji: 'shinjuku made ichimai kudasai', english: 'One ticket to Shinjuku please', type: 'phrase' },
  { japanese: 'この電車は東京に行きますか', romaji: 'kono densha wa toukyou ni ikimasu ka', english: 'Does this train go to Tokyo?', type: 'phrase' },
  { japanese: '次の駅は何ですか', romaji: 'tsugi no eki wa nan desu ka', english: 'What is the next station?', type: 'phrase' },
  { japanese: '乗り換えが必要ですか', romaji: 'norikae ga hitsuyou desu ka', english: 'Do I need to transfer?', type: 'phrase' },
  { japanese: 'どこで降りますか', romaji: 'doko de orimasu ka', english: 'Where should I get off?', type: 'phrase' },
  { japanese: 'ICカードはありますか', romaji: 'ai shii kaado wa arimasu ka', english: 'Do you have an IC card?', type: 'phrase' },
  { japanese: 'スイカをチャージしたいです', romaji: 'suika wo chaaji shitai desu', english: 'I want to charge my Suica', type: 'phrase' },

  // Transportation - Taxi
  { japanese: 'タクシー乗り場はどこですか', romaji: 'takushii noriba wa doko desu ka', english: 'Where is the taxi stand?', type: 'phrase' },
  { japanese: 'ここまでお願いします', romaji: 'koko made onegaishimasu', english: 'To here please', type: 'phrase' },
  { japanese: 'この住所までお願いします', romaji: 'kono juusho made onegaishimasu', english: 'To this address please', type: 'phrase' },
  { japanese: 'ここで止めてください', romaji: 'koko de tomete kudasai', english: 'Please stop here', type: 'phrase' },
  { japanese: 'いくらかかりますか', romaji: 'ikura kakarimasu ka', english: 'How much will it cost?', type: 'phrase' },
  { japanese: 'レシートをください', romaji: 'reshiito wo kudasai', english: 'Receipt please', type: 'phrase' },

  // Transportation - Bus
  { japanese: 'バス停はどこですか', romaji: 'basutei wa doko desu ka', english: 'Where is the bus stop?', type: 'phrase' },
  { japanese: 'このバスは渋谷に行きますか', romaji: 'kono basu wa shibuya ni ikimasu ka', english: 'Does this bus go to Shibuya?', type: 'phrase' },
  { japanese: '運賃はいくらですか', romaji: 'unchin wa ikura desu ka', english: 'How much is the fare?', type: 'phrase' },
  { japanese: '次のバスは何時ですか', romaji: 'tsugi no basu wa nanji desu ka', english: 'When is the next bus?', type: 'phrase' },

  // Transportation - Airport
  { japanese: '空港はどこですか', romaji: 'kuukou wa doko desu ka', english: 'Where is the airport?', type: 'phrase' },
  { japanese: 'チェックインカウンターはどこですか', romaji: 'chekku in kauntaa wa doko desu ka', english: 'Where is check-in?', type: 'phrase' },
  { japanese: '搭乗券をお願いします', romaji: 'toujouken wo onegaishimasu', english: 'Boarding pass please', type: 'phrase' },
  { japanese: '窓側の席をお願いします', romaji: 'madogawa no seki wo onegaishimasu', english: 'Window seat please', type: 'phrase' },
  { japanese: '通路側の席をお願いします', romaji: 'tsuurogawa no seki wo onegaishimasu', english: 'Aisle seat please', type: 'phrase' },
  { japanese: '手荷物預かり所はどこですか', romaji: 'tenimotsu azukarisho wa doko desu ka', english: 'Where is baggage claim?', type: 'phrase' },

  // Hotel/Accommodation
  { japanese: 'チェックインお願いします', romaji: 'chekku in onegaishimasu', english: 'Check in please', type: 'phrase' },
  { japanese: '予約しています', romaji: 'yoyaku shite imasu', english: 'I have a reservation', type: 'phrase' },
  { japanese: 'チェックアウトお願いします', romaji: 'chekku auto onegaishimasu', english: 'Check out please', type: 'phrase' },
  { japanese: '部屋の鍵をください', romaji: 'heya no kagi wo kudasai', english: 'Room key please', type: 'phrase' },
  { japanese: 'WiFiのパスワードは何ですか', romaji: 'waifai no pasuwaado wa nan desu ka', english: 'What is the WiFi password?', type: 'phrase' },
  { japanese: '朝食は含まれていますか', romaji: 'choushoku wa fukumarete imasu ka', english: 'Is breakfast included?', type: 'phrase' },
  { japanese: '朝食は何時からですか', romaji: 'choushoku wa nanji kara desu ka', english: 'What time is breakfast?', type: 'phrase' },
  { japanese: 'エアコンが動きません', romaji: 'eakon ga ugokimasen', english: 'The AC doesn\'t work', type: 'phrase' },
  { japanese: 'タオルをください', romaji: 'taoru wo kudasai', english: 'Towels please', type: 'phrase' },
  { japanese: '荷物を預けられますか', romaji: 'nimotsu wo azukeraremasu ka', english: 'Can I leave my luggage?', type: 'phrase' },
  { japanese: '延長できますか', romaji: 'enchou dekimasu ka', english: 'Can I extend my stay?', type: 'phrase' },
  { japanese: '部屋を変えてください', romaji: 'heya wo kaete kudasai', english: 'Please change my room', type: 'phrase' },

  // Restaurant/Food
  { japanese: 'いただきます', romaji: 'itadakimasu', english: 'Let\'s eat (before meal)', type: 'phrase' },
  { japanese: 'ごちそうさまでした', romaji: 'gochisousama deshita', english: 'Thank you for the meal', type: 'phrase' },
  { japanese: '予約していません', romaji: 'yoyaku shite imasen', english: 'I don\'t have a reservation', type: 'phrase' },
  { japanese: '二人です', romaji: 'futari desu', english: 'Two people', type: 'phrase' },
  { japanese: 'メニューをください', romaji: 'menyuu wo kudasai', english: 'Menu please', type: 'phrase' },
  { japanese: '英語のメニューはありますか', romaji: 'eigo no menyuu wa arimasu ka', english: 'Do you have an English menu?', type: 'phrase' },
  { japanese: '写真のメニューはありますか', romaji: 'shashin no menyuu wa arimasu ka', english: 'Do you have a picture menu?', type: 'phrase' },
  { japanese: 'おすすめは何ですか', romaji: 'osusume wa nan desu ka', english: 'What do you recommend?', type: 'phrase' },
  { japanese: 'これをください', romaji: 'kore wo kudasai', english: 'This please', type: 'phrase' },
  { japanese: '水をください', romaji: 'mizu wo kudasai', english: 'Water please', type: 'phrase' },
  { japanese: 'お茶をください', romaji: 'ocha wo kudasai', english: 'Tea please', type: 'phrase' },
  { japanese: 'ビールをください', romaji: 'biiru wo kudasai', english: 'Beer please', type: 'phrase' },
  { japanese: '美味しい', romaji: 'oishii', english: 'Delicious', type: 'phrase' },
  { japanese: 'お腹がすきました', romaji: 'onaka ga sukimashita', english: 'I\'m hungry', type: 'phrase' },
  { japanese: 'お会計お願いします', romaji: 'okaikei onegaishimasu', english: 'Check please', type: 'phrase' },
  { japanese: 'クレジットカードは使えますか', romaji: 'kurejitto kaado wa tsukaemasu ka', english: 'Can I use credit card?', type: 'phrase' },
  { japanese: '別々に払います', romaji: 'betsubetsu ni haraimasu', english: 'We\'ll pay separately', type: 'phrase' },
  { japanese: '辛くしないでください', romaji: 'karaku shinaide kudasai', english: 'Not spicy please', type: 'phrase' },
  { japanese: 'アレルギーがあります', romaji: 'arerugii ga arimasu', english: 'I have allergies', type: 'phrase' },
  { japanese: 'ベジタリアンです', romaji: 'bejitarian desu', english: 'I\'m vegetarian', type: 'phrase' },
  { japanese: '豚肉は食べられません', romaji: 'butaniku wa taberaremasen', english: 'I can\'t eat pork', type: 'phrase' },

  // Shopping
  { japanese: 'いくらですか', romaji: 'ikura desu ka', english: 'How much is it?', type: 'phrase' },
  { japanese: 'これをください', romaji: 'kore wo kudasai', english: 'I\'ll take this please', type: 'phrase' },
  { japanese: '見てるだけです', romaji: 'miteru dake desu', english: 'Just looking', type: 'phrase' },
  { japanese: '試着できますか', romaji: 'shichaku dekimasu ka', english: 'Can I try it on?', type: 'phrase' },
  { japanese: '試着室はどこですか', romaji: 'shichakushitsu wa doko desu ka', english: 'Where is the fitting room?', type: 'phrase' },
  { japanese: 'もっと大きいサイズはありますか', romaji: 'motto ookii saizu wa arimasu ka', english: 'Do you have a larger size?', type: 'phrase' },
  { japanese: 'もっと小さいサイズはありますか', romaji: 'motto chiisai saizu wa arimasu ka', english: 'Do you have a smaller size?', type: 'phrase' },
  { japanese: '他の色はありますか', romaji: 'hoka no iro wa arimasu ka', english: 'Do you have other colors?', type: 'phrase' },
  { japanese: '安くなりますか', romaji: 'yasuku narimasu ka', english: 'Can you make it cheaper?', type: 'phrase' },
  { japanese: '免税できますか', romaji: 'menzei dekimasu ka', english: 'Can I get tax free?', type: 'phrase' },
  { japanese: '袋をください', romaji: 'fukuro wo kudasai', english: 'Bag please', type: 'phrase' },
  { japanese: 'プレゼント用に包んでください', romaji: 'purezento you ni tsutsunde kudasai', english: 'Gift wrap please', type: 'phrase' },
  { japanese: '返品できますか', romaji: 'henpin dekimasu ka', english: 'Can I return this?', type: 'phrase' },

  // Directions
  { japanese: 'トイレはどこですか', romaji: 'toire wa doko desu ka', english: 'Where is the bathroom?', type: 'phrase' },
  { japanese: 'ここはどこですか', romaji: 'koko wa doko desu ka', english: 'Where am I?', type: 'phrase' },
  { japanese: 'どうやって行きますか', romaji: 'douyatte ikimasu ka', english: 'How do I get there?', type: 'phrase' },
  { japanese: '歩いて行けますか', romaji: 'aruite ikemasu ka', english: 'Can I walk there?', type: 'phrase' },
  { japanese: '近いですか', romaji: 'chikai desu ka', english: 'Is it close?', type: 'phrase' },
  { japanese: '遠いですか', romaji: 'tooi desu ka', english: 'Is it far?', type: 'phrase' },
  { japanese: 'まっすぐ行ってください', romaji: 'massugu itte kudasai', english: 'Go straight', type: 'phrase' },
  { japanese: '右に曲がってください', romaji: 'migi ni magatte kudasai', english: 'Turn right', type: 'phrase' },
  { japanese: '左に曲がってください', romaji: 'hidari ni magatte kudasai', english: 'Turn left', type: 'phrase' },
  { japanese: '地図を描いてください', romaji: 'chizu wo kaite kudasai', english: 'Please draw a map', type: 'phrase' },
  { japanese: '道に迷いました', romaji: 'michi ni mayoimashita', english: 'I\'m lost', type: 'phrase' },

  // Tourist Attractions
  { japanese: '入場料はいくらですか', romaji: 'nyuujouryou wa ikura desu ka', english: 'How much is admission?', type: 'phrase' },
  { japanese: '何時までですか', romaji: 'nanji made desu ka', english: 'Until what time?', type: 'phrase' },
  { japanese: '写真を撮ってもいいですか', romaji: 'shashin wo totte mo ii desu ka', english: 'Can I take photos?', type: 'phrase' },
  { japanese: '写真を撮ってください', romaji: 'shashin wo totte kudasai', english: 'Please take my photo', type: 'phrase' },
  { japanese: 'パンフレットをください', romaji: 'panfuretto wo kudasai', english: 'Pamphlet please', type: 'phrase' },
  { japanese: 'オーディオガイドはありますか', romaji: 'oodio gaido wa arimasu ka', english: 'Do you have audio guide?', type: 'phrase' },
  { japanese: 'ツアーはありますか', romaji: 'tsuaa wa arimasu ka', english: 'Are there tours?', type: 'phrase' },

  // Emergency/Medical
  { japanese: '助けて', romaji: 'tasukete', english: 'Help!', type: 'phrase' },
  { japanese: '警察を呼んでください', romaji: 'keisatsu wo yonde kudasai', english: 'Call the police', type: 'phrase' },
  { japanese: '救急車を呼んでください', romaji: 'kyuukyuusha wo yonde kudasai', english: 'Call an ambulance', type: 'phrase' },
  { japanese: '病院はどこですか', romaji: 'byouin wa doko desu ka', english: 'Where is the hospital?', type: 'phrase' },
  { japanese: '薬局はどこですか', romaji: 'yakkyoku wa doko desu ka', english: 'Where is the pharmacy?', type: 'phrase' },
  { japanese: '気分が悪いです', romaji: 'kibun ga warui desu', english: 'I feel sick', type: 'phrase' },
  { japanese: '頭が痛いです', romaji: 'atama ga itai desu', english: 'I have a headache', type: 'phrase' },
  { japanese: 'お腹が痛いです', romaji: 'onaka ga itai desu', english: 'I have a stomachache', type: 'phrase' },
  { japanese: '熱があります', romaji: 'netsu ga arimasu', english: 'I have a fever', type: 'phrase' },
  { japanese: '薬はありますか', romaji: 'kusuri wa arimasu ka', english: 'Do you have medicine?', type: 'phrase' },
  { japanese: '保険証を持っています', romaji: 'hokenshou wo motte imasu', english: 'I have insurance', type: 'phrase' },
  { japanese: '英語を話せる医者はいますか', romaji: 'eigo wo hanaseru isha wa imasu ka', english: 'Is there an English-speaking doctor?', type: 'phrase' },

  // Problems
  { japanese: '困っています', romaji: 'komatte imasu', english: 'I\'m in trouble', type: 'phrase' },
  { japanese: 'パスポートをなくしました', romaji: 'pasupooto wo nakushimashita', english: 'I lost my passport', type: 'phrase' },
  { japanese: '財布をなくしました', romaji: 'saifu wo nakushimashita', english: 'I lost my wallet', type: 'phrase' },
  { japanese: '携帯をなくしました', romaji: 'keitai wo nakushimashita', english: 'I lost my phone', type: 'phrase' },
  { japanese: '盗まれました', romaji: 'nusumaremashita', english: 'I was robbed', type: 'phrase' },
  { japanese: '大使館はどこですか', romaji: 'taishikan wa doko desu ka', english: 'Where is the embassy?', type: 'phrase' },

  // Numbers & Time
  { japanese: '今何時ですか', romaji: 'ima nanji desu ka', english: 'What time is it now?', type: 'phrase' },
  { japanese: '何時に開きますか', romaji: 'nanji ni akimasu ka', english: 'What time does it open?', type: 'phrase' },
  { japanese: '何時に閉まりますか', romaji: 'nanji ni shimarimasu ka', english: 'What time does it close?', type: 'phrase' },
  { japanese: 'どのくらいかかりますか', romaji: 'dono kurai kakarimasu ka', english: 'How long does it take?', type: 'phrase' },
  { japanese: '今日', romaji: 'kyou', english: 'Today', type: 'phrase' },
  { japanese: '明日', romaji: 'ashita', english: 'Tomorrow', type: 'phrase' },
  { japanese: '昨日', romaji: 'kinou', english: 'Yesterday', type: 'phrase' },

  // Common Requests
  { japanese: 'ちょっと待ってください', romaji: 'chotto matte kudasai', english: 'Please wait a moment', type: 'phrase' },
  { japanese: 'もう一回言ってください', romaji: 'mou ikkai itte kudasai', english: 'Please say it again', type: 'phrase' },
  { japanese: '見せてください', romaji: 'misete kudasai', english: 'Please show me', type: 'phrase' },
  { japanese: '教えてください', romaji: 'oshiete kudasai', english: 'Please tell me', type: 'phrase' },
  { japanese: '手伝ってください', romaji: 'tetsudatte kudasai', english: 'Please help me', type: 'phrase' },
  { japanese: '大丈夫です', romaji: 'daijoubu desu', english: 'It\'s okay / I\'m fine', type: 'phrase' },
  { japanese: '結構です', romaji: 'kekkou desu', english: 'No thank you', type: 'phrase' },

  // Miscellaneous
  { japanese: 'お名前は何ですか', romaji: 'onamae wa nan desu ka', english: 'What\'s your name?', type: 'phrase' },
  { japanese: '私の名前は', romaji: 'watashi no namae wa', english: 'My name is', type: 'phrase' },
  { japanese: 'どこから来ましたか', romaji: 'doko kara kimashita ka', english: 'Where are you from?', type: 'phrase' },
  { japanese: 'アメリカから来ました', romaji: 'amerika kara kimashita', english: 'I\'m from America', type: 'phrase' },
  { japanese: '観光です', romaji: 'kankou desu', english: 'I\'m a tourist', type: 'phrase' },
  { japanese: '仕事です', romaji: 'shigoto desu', english: 'I\'m here for work', type: 'phrase' },
  { japanese: '日本は初めてです', romaji: 'nihon wa hajimete desu', english: 'First time in Japan', type: 'phrase' },
  { japanese: '何日間滞在しますか', romaji: 'nannichi kan taizai shimasu ka', english: 'How many days are you staying?', type: 'phrase' },
  { japanese: '一週間滞在します', romaji: 'isshuukan taizai shimasu', english: 'I\'m staying for a week', type: 'phrase' },
  { japanese: '楽しんでください', romaji: 'tanoshinde kudasai', english: 'Please enjoy', type: 'phrase' },
  { japanese: '気をつけて', romaji: 'ki wo tsukete', english: 'Be careful / Take care', type: 'phrase' },
  { japanese: '行ってきます', romaji: 'itte kimasu', english: 'I\'m leaving (will come back)', type: 'phrase' },
  { japanese: '行ってらっしゃい', romaji: 'itte rasshai', english: 'Have a good trip', type: 'phrase' },
  { japanese: 'ただいま', romaji: 'tadaima', english: 'I\'m back', type: 'phrase' },
  { japanese: 'お帰りなさい', romaji: 'okaeri nasai', english: 'Welcome back', type: 'phrase' },
  { japanese: 'お邪魔します', romaji: 'ojama shimasu', english: 'Excuse me (entering)', type: 'phrase' },
  { japanese: 'お邪魔しました', romaji: 'ojama shimashita', english: 'Thank you (leaving)', type: 'phrase' },
  { japanese: 'お疲れ様でした', romaji: 'otsukaresama deshita', english: 'Good work / Thank you', type: 'phrase' },
  { japanese: '頑張って', romaji: 'ganbatte', english: 'Good luck / Do your best', type: 'phrase' },
  { japanese: 'お先に失礼します', romaji: 'osaki ni shitsurei shimasu', english: 'Excuse me for leaving first', type: 'phrase' },

  // Internet & Technology
  { japanese: 'WiFiはありますか', romaji: 'waifai wa arimasu ka', english: 'Is there WiFi?', type: 'phrase' },
  { japanese: 'パスワードは何ですか', romaji: 'pasuwaado wa nan desu ka', english: 'What is the password?', type: 'phrase' },
  { japanese: '充電できますか', romaji: 'juuden dekimasu ka', english: 'Can I charge?', type: 'phrase' },
  { japanese: 'コンセントはどこですか', romaji: 'konsento wa doko desu ka', english: 'Where is the outlet?', type: 'phrase' },
  { japanese: 'SIMカードはどこで買えますか', romaji: 'shimu kaado wa doko de kaemasu ka', english: 'Where can I buy a SIM card?', type: 'phrase' },

  // Weather & Temperature
  { japanese: '暑いですね', romaji: 'atsui desu ne', english: 'It\'s hot', type: 'phrase' },
  { japanese: '寒いですね', romaji: 'samui desu ne', english: 'It\'s cold', type: 'phrase' },
  { japanese: '天気が良いですね', romaji: 'tenki ga yoi desu ne', english: 'Nice weather', type: 'phrase' },
  { japanese: '雨が降っています', romaji: 'ame ga futte imasu', english: 'It\'s raining', type: 'phrase' },
  { japanese: '傘はありますか', romaji: 'kasa wa arimasu ka', english: 'Do you have an umbrella?', type: 'phrase' }
];

// Combine all data
export const allData = [...hiragana, ...katakana, ...phrases];
